title: 2jiho입니다. # name of the site
author: 2jiho # name of site's author
email: blog@2jiho.com # email of site's author
url: https://blog.2jiho.com # root address of the site
baseurl: ""
description: > # description of the site (multiple lines allowed)
  2jiho의 저장소

remote_theme: riggraz/no-style-please
